version: '3.7'
services:
  mysql:
    image: mysql:9.0.1
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  node-app:
    build: 
      context: ./gate-simulator
      dockerfile: Dockerfile
    image: node-app:1.0
    ports:
      - '9999:9999'
  postgresql:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
      - POSTGRES_USER=app
